replicaCount: 1
image:
  repository: ghcr.io/houses-on-the-air/adif-combiner
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  port: 8000
resources:
  limits:
    cpu: "1000m"
    memory: "2056Mi"
  requests:
    cpu: "250m"
    memory: "512Mi"
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 50
  targetCPUUtilizationPercentage: 70
